<a href="https://colab.research.google.com/github/Gaks978/Data-Science-Projects/blob/main/Numpy_essentials_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What You're Aiming For

The objective  is to utilize the NumPy library to perform detailed analysis on a dataset of student grades. This includes calculating statistical measures, identifying trends, and extracting subsets of data to understand the performance and achievements of students within a specific grading scale.


Instructions

Create a numpy array called "grades" that contains the following grades: [85, 90, 88, 92, 95, 80, 75, 98, 89, 83]

Import the numpy library and create the "grades" array as specified above.

Use numpy functions to calculate the mean, median, and standard deviation of the grades.

Use numpy function to find the maximum and minimum of the grades.

Use numpy function to sort the grades in ascending order.

Use numpy function to find the index of the highest grade in the array.

Use numpy function to count the number of students who scored above 90.

Use numpy function to calculate the percentage of students who scored above 90.

Use numpy function to calculate the percentage of students who scored below 75.

Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".

Create a new array called "passing_grades" that contains all the grades above 75.

Print the result of all the above steps.

Note:

to calculate percentage use numpy.mean(grades > 90) * 100

to extract the grades above 90 use grades[grades > 90]

to extract the grades above 75 use grades[grades > 75]

You can use other numpy functions as well to analyze the data as you want. The above steps are just examples of what can be done.

In [ ]:
import numpy as np
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
print(grades)

# calculating the mean,median and the standard deviation
np.mean(grades)

[85 90 88 92 95 80 75 98 89 83]


np.float64(87.5)

In [ ]:
np.median(grades)

np.float64(88.5)

In [ ]:
np.std(grades)

np.float64(6.591661399070799)

In [ ]:
np.max(grades)

np.int64(98)

In [ ]:
np.min(grades)

np.int64(75)

In [ ]:
np.sort(grades)

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [ ]:
np.argmax(grades)

np.int64(7)

In [ ]:
students_above_90 = np.sum(grades > 90)
print(students_above_90)

3


In [ ]:
percentage_of_students_above_90 = np.mean(grades > 90) * 100
print(percentage_of_students_above_90)

30.0


In [ ]:
percentage_of_students_below_75 = np.mean(grades < 75) * 100
print(percentage_of_students_below_75)

0.0


In [ ]:
high_performers = grades[grades > 90]
print(high_performers)

[92 95 98]


In [ ]:
passing_grades = grades[grades > 75]
print(passing_grades)

[85 90 88 92 95 80 98 89 83]
