<a href="https://colab.research.google.com/github/Gaks978/DML-Checkpoint/blob/main/Numpy_essentials_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
print(grades)

# calculating the mean,median and the standard deviation
np.mean(grades)

[85 90 88 92 95 80 75 98 89 83]


np.float64(87.5)

In [3]:
np.median(grades)

np.float64(88.5)

In [4]:
np.std(grades)

np.float64(6.591661399070799)

In [5]:
np.max(grades)

np.int64(98)

In [6]:
np.min(grades)

np.int64(75)

In [7]:
np.sort(grades)

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [8]:
np.argmax(grades)

np.int64(7)

In [9]:
students_above_90 = np.sum(grades > 90)
print(students_above_90)

3


In [10]:
percentage_of_students_above_90 = np.mean(grades > 90) * 100
print(percentage_of_students_above_90)

30.0


In [11]:
percentage_of_students_below_75 = np.mean(grades < 75) * 100
print(percentage_of_students_below_75)

0.0


In [12]:
high_performers = grades[grades > 90]
print(high_performers)

[92 95 98]


In [13]:
passing_grades = grades[grades > 75]
print(passing_grades)

[85 90 88 92 95 80 98 89 83]
